typography_spectrum: 0.15428755861006235
color:
  brandStrength: 0.5453438612324472
  lightness: 0.2765594332011435
  saturation: 0.7816449567594446
  rhythmicContrast: 0.6510701727841308
  brandColors:
    - '#A1C3E9'
    - '#10120D'
    - '#7F7E83'
    - '#4B5265'
    - '#FFFFFF'
github: true
layout_spectrum: 0.9514371809890807
author:
  name: VICENTE
  email: vicentejover.edu@gmail.com
  url: thegrid.ai/mrjover
name: mr.jover
title: Vicente Jover
content: []
description: Life in Canada
purpose:
  - type: contact
    url: 'mailto:vicentejover.edu@gmail.com'
    label: Contact me!
