layout_spectrum: 0.6233986468126278
typography_spectrum: 0.18902073312145057
color:
  brandStrength: 0.9532147318470559
  lightness: 0.17297118332882477
  saturation: 0.46920279804239107
  rhythmicContrast: 0.5272311964854229
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
github: true
author:
  name: VICENTE
  email: vicentejover.edu@gmail.com
  url: thegrid.ai/mrjover
name: mr.jover
title: Vicente Jover
content: []
description: Life in Canada
purpose:
  - type: contact
    url: 'mailto:vicentejover.edu@gmail.com'
    label: Contact me!
